### ISSUE TITLE
Drawer does not animate in when snap points are set

### ISSUE THREAD

**Issue by riicodespretty** [radix-vue/vaul-vue#108]
When `snapPoints` are provided in props, the drawer appears instantly without an animate-in effect, though it still animates out. This makes the UX feel inconsistent.

**Cause:**  
The CSS for snap point drawers doesn't define an animation with open/close states:  
https://github.com/unovue/vaul-vue/blob/1b1f6dfdba6a775410508884097443d35c9a8690/packages/vaul-vue/src/style.css#L37-L51

By contrast, drawers without snap points _do_ define an animation depending on open/close states:
https://github.com/unovue/vaul-vue/blob/1b1f6dfdba6a775410508884097443d35c9a8690/packages/vaul-vue/src/style.css#L9-L35

---

### ✅ Workaround

The drawer already sets `--snap-point-height`, so we can conveniently reference it to write an animate-in effect. I feel like this should have been included out-of-the-box.

Here's an example for a snap point bottom drawer:

```css
[data-vaul-drawer][data-vaul-snap-points=true][data-vaul-drawer-direction=bottom][data-state=open] {
  animation-name: slideFromBottomToSnapPoint;
}

@keyframes slideFromBottomToSnapPoint {
  from {
    transform: translate3d(0, var(--initial-transform, 100%), 0);
  }
  to {
    transform: translate3d(0, var(--snap-point-height, 0), 0);
  }
}
```

This works for `@nuxt/ui` `<UDrawer>` component too.
